service: api-maquinas-industriales

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: offline
  region: us-west-1
  memorySize: 512
  timeout: 20
  environment: ${file(serverless.env.yml)}



plugins:
  - serverless-s3-local
  - serverless-offline-ssm
  - serverless-offline

custom:
  serverless-offline-ssm:
    stages:
      - offline
    ssm:
      "/hello_test": "HELLO SSM"
  serverless-offline:
    httpPort: 4000

functions:
  bucketS3:
    handler: src/lambdas/bucketS3.config
    events:
      - s3: local-bucket
        event: s3:*
  hello:
    handler: src/lambdas/hello.msg
    events:
      - httpApi:
          method: GET
          path: hello
          private: true

resources:
  - ${file(src/resources/api-gateway.yml)}
  - ${file(src/resources/bucket-s3.yml)}
